/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do FSC
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  id: string;
  name: string;
  order: number;
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  id: string;
  name: string;
  isRest: boolean;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  userId: string;
  isActive: boolean;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export const GetWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDay200ExercisesItem = {
  id: string;
  name: string;
  order: number;
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDay200SessionsItem = {
  id: string;
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  id: string;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDay200WeekDay;
  exercises: GetWorkoutDay200ExercisesItem[];
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutSessionId: string;
};

export type StartWorkoutSession400 = {
  error: string;
  code: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  startedAt: string;
  completedAt: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetHomeData200TodayWorkoutDay = {
  workoutPlanId: string;
  id: string;
  name: string;
  isRest: boolean;
  weekDay:
    | "MONDAY"
    | "TUESDAY"
    | "WEDNESDAY"
    | "THURSDAY"
    | "FRIDAY"
    | "SATURDAY"
    | "SUNDAY";
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercisesCount: number;
} | null;

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  activeWorkoutPlanId: string;
  /** @nullable */
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats404 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetMe200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type UpsertMeBody = {
  /** @maximum 9007199254740991 */
  weightInGrams: number;
  /** @maximum 9007199254740991 */
  heightInCentimeters: number;
  /** @maximum 9007199254740991 */
  age: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertMe200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertMe401 = {
  error: string;
  code: string;
};

export type UpsertMe500 = {
  error: string;
  code: string;
};

export type PostAi401 = {
  error: string;
};

export type PostAi500 = {
  error: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary List all workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[];
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plan/?${stringifiedParams}`
    : `/workout-plan/`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plan/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get workout plan by id
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError;

export const getGetWorkoutPlanUrl = (id: string) => {
  return `/workout-plan/${id}`;
};

export const getWorkoutPlan = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(getGetWorkoutPlanUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get workout day details
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError;

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plan/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse400 = {
  data: StartWorkoutSession400;
  status: 400;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse400
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plan/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200;
  status: 200;
};

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401;
  status: 401;
};

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404;
  status: 404;
};

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500;
  status: 500;
};

export type updateWorkoutSessionResponseSuccess =
  updateWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type updateWorkoutSessionResponseError = (
  | updateWorkoutSessionResponse401
  | updateWorkoutSessionResponse404
  | updateWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse =
  | updateWorkoutSessionResponseSuccess
  | updateWorkoutSessionResponseError;

export const getUpdateWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plan/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const updateWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
  return customFetch<updateWorkoutSessionResponse>(
    getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutSessionBody),
    },
  );
};

/**
 * @summary Get home data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get workout statistics
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse404 = {
  data: GetStats404;
  status: 404;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse404
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get my train data
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/me/`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert my train data
 */
export type upsertMeResponse200 = {
  data: UpsertMe200;
  status: 200;
};

export type upsertMeResponse401 = {
  data: UpsertMe401;
  status: 401;
};

export type upsertMeResponse500 = {
  data: UpsertMe500;
  status: 500;
};

export type upsertMeResponseSuccess = upsertMeResponse200 & {
  headers: Headers;
};
export type upsertMeResponseError = (
  | upsertMeResponse401
  | upsertMeResponse500
) & {
  headers: Headers;
};

export type upsertMeResponse = upsertMeResponseSuccess | upsertMeResponseError;

export const getUpsertMeUrl = () => {
  return `/me/`;
};

export const upsertMe = async (
  upsertMeBody: UpsertMeBody,
  options?: RequestInit,
): Promise<upsertMeResponse> => {
  return customFetch<upsertMeResponse>(getUpsertMeUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertMeBody),
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse401 = {
  data: PostAi401;
  status: 401;
};

export type postAiResponse500 = {
  data: PostAi500;
  status: 500;
};
export type postAiResponseError = (postAiResponse401 | postAiResponse500) & {
  headers: Headers;
};

export type postAiResponse = postAiResponseError;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
  });
};

/**
 * Hello world
 */
export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
